version: "3"

# Service called app and build in the directory we currently are in
# Run on port 8050
# Command is the commands that is run on the docker container within a shell
# Run docker-compose build to run docker configuration
services:
  app:
    build:
      context: .
    ports:
      - "8050:8050"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8050"